FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["ApiTeste/ApiTeste.csproj", "ApiTeste/"]
RUN dotnet restore "ApiTeste/ApiTeste.csproj"
COPY . .
WORKDIR "/src/ApiTeste"
RUN dotnet build "ApiTeste.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "ApiTeste.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ApiTeste.dll"]